### ISSUE TITLE
Add a `ww deactivate`-like command

### ISSUE THREAD

**Issue by JPTIZ** [ESSS/ww#9]
Like `conda deactivate`, for example, it should undo the changes. Could make use of a `ww_deactivate` script on workspaces.

**Comment by prusse-martin** [comment]
This easily could lead to inconsistencies.
I use to scrap a terminal and start a new one every time I need to switch "ww".

**Comment by JPTIZ** [comment]
> This easily could lead to inconsistencies.
Agreed.
> I use to scrap a terminal and start a new one every time I need to switch "ww".
:thinking: Seems easier indeed. Do you think this is discussible or can I close this issue as "wontfix"?

**Comment by prusse-martin** [comment]
I would prefer to mark as "wontfix".
